const $ = (selector) => document.querySelector(selector);
const carGrid = $('#car-grid'), modal = $('#car-modal'), modalContent = $('#modal-content');
const filterButtons = [...document.querySelectorAll('.filter-btn')];
let cars = [], currentFilter = 'All', currentSearch = '', selectedCar = null, lastFocusedElement = null, previousOverflow = '';

const escapeHtml = (value) => String(value ?? '').replace(/[&<>'"]/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const phone = '959403718599';
function setFilter(button) { filterButtons.forEach((b) => { const active = b === button; b.classList.toggle('is-active', active); b.setAttribute('aria-pressed', String(active)); }); }
function filteredCars() { const q = currentSearch.trim().toLowerCase(); return cars.filter((car) => (currentFilter === 'All' || car.brand === currentFilter) && [car.brand, car.name, car.model].join(' ').toLowerCase().includes(q)); }
function renderCars() {
  const result = filteredCars(); $('#data-status').textContent = `${result.length} vehicle${result.length === 1 ? '' : 's'}`; $('#results-status').textContent = result.length ? `${result.length} vehicles shown` : 'No vehicles found';
  if (!result.length) { carGrid.innerHTML = '<p class="col-span-full text-center text-slate-400 py-10">No vehicles found matching your search.</p>'; return; }
  carGrid.innerHTML = result.map((car) => { const image = car.images[0]?.src || ''; return `<article class="glass-card rounded-3xl overflow-hidden glass-card--interactive"><button type="button" class="relative block w-full text-left group" data-action="details" data-car-id="${car.id}" aria-label="View details for ${escapeHtml(car.name)}"><div class="relative overflow-hidden h-56"><img src="${escapeHtml(image)}" alt="${escapeHtml(car.name)}" loading="lazy" decoding="async" width="800" height="600" class="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"><div class="absolute inset-0 bg-gradient-to-t from-black/80 via-black/10 to-transparent"></div></div><div class="p-5"><div class="flex items-center justify-between gap-2 mb-4"><span class="text-xs font-semibold uppercase tracking-[0.2em] text-blue-300">${escapeHtml(car.brand)}</span><span class="text-xs text-slate-400">${escapeHtml(car.model)}</span></div><h3 class="text-xl font-semibold text-white mb-4">${escapeHtml(car.name)}</h3><div class="grid grid-cols-2 gap-2 text-xs text-slate-300"><span class="bg-white/5 rounded-lg px-2 py-2">⚙ ${escapeHtml(car.engine)}</span><span class="bg-white/5 rounded-lg px-2 py-2">▣ ${escapeHtml(car.model)}</span><span class="bg-white/5 rounded-lg px-2 py-2">♙ ${escapeHtml(car.seats)} seats</span><span class="bg-white/5 rounded-lg px-2 py-2">⚡ ${escapeHtml(car.hp)}</span></div></div></button><div class="p-5 pt-0"><button type="button" class="w-full rounded-xl bg-blue-600 px-3 py-2 text-sm font-medium text-white hover:bg-blue-500 transition-colors" data-action="details" data-car-id="${car.id}">Details</button></div></article>`; }).join('');
}
function specs(car) { return [['speed','Engine',car.engine],['calendar_month','Model',car.model],['airline_seat_recline_normal','Seats',car.seats],['bolt','Horsepower',car.hp],['account_tree','Transmission',car.gear],['straighten','Dimensions',car.dimensions],['height','Ground clearance',car.groundClearance]].map(([icon,label,value]) => `<li class="flex items-center justify-between gap-3 border-b border-white/10 pb-3"><span class="flex items-center gap-2 text-slate-400"><span class="material-symbols-outlined text-[18px] text-blue-400" aria-hidden="true">${icon}</span>${label}</span><strong class="text-white text-right">${escapeHtml(value)}</strong></li>`).join(''); }
function updateModal(car) { const first = car.images[0]; $('#modal-car-title').textContent = car.name; $('#modal-main-image').src = first.src; $('#modal-main-image').alt = `${car.name} ${first.label}`; $('#modal-view-label').textContent = first.label; $('#modal-specs-list').innerHTML = specs(car); $('#modal-features').innerHTML = (car.features || ['Modern aesthetic design','Advanced safety systems','Spacious premium interior','Smart connectivity features']).map((f) => `<li class="flex items-center gap-2"><span class="material-symbols-outlined text-[16px] text-blue-400" aria-hidden="true">check_circle</span>${escapeHtml(f)}</li>`).join(''); $('#modal-thumbnails').innerHTML = car.images.map((image, index) => `<button type="button" data-image-index="${index}" aria-label="Show ${escapeHtml(image.label)}" aria-pressed="${index === 0}" class="thumb ${index ? 'opacity-70 border-transparent' : 'border-blue-500'} border-2 rounded-lg overflow-hidden flex-shrink-0 w-24 h-16"><img src="${escapeHtml(image.src)}" alt="${escapeHtml(car.name)} ${escapeHtml(image.label)}" class="w-full h-full object-cover" loading="lazy" decoding="async"></button>`).join(''); }
function openModal(id) { selectedCar = cars.find((car) => car.id === id); if (!selectedCar) return; lastFocusedElement = document.activeElement; updateModal(selectedCar); modal.classList.remove('hidden','opacity-0'); modal.classList.add('flex'); requestAnimationFrame(() => { modal.classList.add('opacity-100'); modalContent.classList.replace('scale-95','scale-100'); }); previousOverflow = document.body.style.overflow; document.body.style.overflow = 'hidden'; $('#modal-close-btn').focus(); }
function closeModal() { modal.classList.remove('opacity-100'); modal.classList.add('opacity-0','hidden'); modal.classList.remove('flex'); modalContent.classList.replace('scale-100','scale-95'); document.body.style.overflow = previousOverflow; selectedCar = null; lastFocusedElement?.focus?.(); }
function contact(car) { const message = encodeURIComponent(`Hello PN7 Automobile, I am interested in the ${car.name}.`); window.location.href = `tel:+${phone}`; }
async function loadCars() { try { const response = await fetch('./cars.json', { cache:'no-cache' }); if (!response.ok) throw new Error('Could not load cars.json'); cars = await response.json(); renderCars(); } catch (error) { carGrid.innerHTML = '<p class="col-span-full text-center text-red-300 py-10">Vehicle data could not be loaded. Please refresh the page.</p>'; console.error(error); } }
filterButtons.forEach((button) => button.addEventListener('click', () => { currentFilter = button.dataset.filter; setFilter(button); renderCars(); }));
$('#search-input').addEventListener('input', (e) => { currentSearch = e.target.value; renderCars(); }); $('#refresh-btn').addEventListener('click', () => { currentFilter = 'All'; currentSearch = ''; $('#search-input').value = ''; setFilter(filterButtons[0]); loadCars(); });
carGrid.addEventListener('click', (event) => { const target = event.target.closest('[data-car-id]'); if (!target) return; const car = cars.find((item) => item.id === Number(target.dataset.carId)); if (target.dataset.action === 'details') openModal(car.id); });
$('#modal-thumbnails').addEventListener('click', (event) => { const thumb = event.target.closest('[data-image-index]'); if (!thumb || !selectedCar) return; const image = selectedCar.images[Number(thumb.dataset.imageIndex)]; $('#modal-main-image').src = image.src; $('#modal-main-image').alt = `${selectedCar.name} ${image.label}`; $('#modal-view-label').textContent = image.label; [...$('#modal-thumbnails').children].forEach((item) => { const active = item === thumb; item.classList.toggle('border-blue-500', active); item.classList.toggle('border-transparent', !active); item.classList.toggle('opacity-70', !active); item.setAttribute('aria-pressed', String(active)); }); });
document.querySelectorAll('[data-close-modal]').forEach((el) => el.addEventListener('click', closeModal)); $('#modal-contact-btn').addEventListener('click', () => { closeModal(); $('#contact').scrollIntoView({behavior:'smooth'}); }); $('#logo-btn').addEventListener('click', () => window.scrollTo({top:0,behavior:'smooth'}));
const menu = $('#mobile-menu'), menuButton = $('#mobile-menu-btn'); function closeMenu() { menu.classList.add('hidden'); menuButton.setAttribute('aria-expanded','false'); menuButton.setAttribute('aria-label','Open navigation menu'); menuButton.querySelector('span').textContent = 'menu'; } menuButton.addEventListener('click', () => { const opening = menu.classList.contains('hidden'); menu.classList.toggle('hidden', !opening); menuButton.setAttribute('aria-expanded', String(opening)); menuButton.setAttribute('aria-label', opening ? 'Close navigation menu' : 'Open navigation menu'); menuButton.querySelector('span').textContent = opening ? 'close' : 'menu'; }); menu.querySelectorAll('a').forEach((link) => link.addEventListener('click', closeMenu));
window.addEventListener('keydown', (event) => { if (event.key === 'Escape') { if (!modal.classList.contains('hidden')) closeModal(); else if (!menu.classList.contains('hidden')) closeMenu(); } });
setFilter(filterButtons[0]); loadCars();
